{% set version = '1.3.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gclus
  version: {{ version|replace("-", "_") }}

source:
  fn: gclus_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/gclus_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gclus/gclus_{{ version }}.tar.gz
  sha256: d6994ee264b464503db005450153973d75eba502e4caaaa6ff99cb95e4376a09

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1001
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-cluster
  run:
    - r-base
    - r-cluster

test:
  commands:
    - $R -e "library('gclus')"           # [not win]
    - "\"%R%\" -e \"library('gclus')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=gclus
  license: GPL (>= 2)
  summary: Orders panels in scatterplot matrices and parallel coordinate displays by some merit
    index. Package contains various indices of merit, ordering functions, and enhanced
    versions of pairs and parcoord which color panels according to their merit level.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
