travis:
  secure:
    BINSTAR_TOKEN: X5Y9ekReT0kOGlx1ONyKN5T5p6rGlBW8WNeVlT1mFjFcdllsvKv0g7JaY5UJ59WgJC/QJ39xq8w/9yvyjQWP7BQpTuCmprgGIvRCw0fm3zyhfRq3tgAZdpykV7F3rbUnxKcSuauzM5U0oLazyJaLkOqNR4W02qryjXS9S8bYTdO+0mYkDE7FB8chYd+EuwJiA+l1BEQxHGHFqnsWPUklP5uR3nhRYIj/D3/OBHQ09vxTC5N1bfUkXiNwSzUERY7u1jKhP4YQbYDl3ib62XfNYu0HuyU+3k5Ma1nWP/ZDjzUvoXopECT2xlVxzi3KpvklM739kOg9+09/0g/1Ckhl5FofpSCjMkE28/lok+Q45bQjigx1Atg2vtXnhcjLAgugwgd9H3R4ruYcg58WtEEcPYz9l923YznPlVHkIRb2TIjEVHhlOZvVMXIcB/GqbGR7YAz8JuWHAPvKgIodYXo+vpGfeV7U7usPYpxGH5HQlV0+ihaYiwEXjLU7ErdQeshgml6g+TtmCD2ymSso9jqerV0MK4ede9K3FXNS48WdhkRH832iPFSqcSrd9VvNl7FD2PCGVfE7dKyynHv2xX5mMN05XyCGuJx/dDD7cvBXT+BiH5vlV8k2Tj3G4FHH43BWg9zlv9fosN4Y4r/secsCm7Sj+O0mcRqNe/gHPOS37WQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
