travis:
  secure:
    BINSTAR_TOKEN: d0V3GEUgknzN4a0UYrfNAUbgrXQZpwfAZEBdKpgbA7rXUMZyYvKN0QZJofDBWbzQdlzT21qhr72+XTuj6GRmz4/aKh5RGRhs+Uzx0WsvRQ2i85gHX3ZNjVTLgMgMJnD9Rhgx5lqkdsEoXvznIjCI3q3I0J+9UBh7f4PBpFOWbIoFPBPj0fwtPjV/FPVOUe9e3DnhiMWY8227xEY9qakRQlvm5LhpSk3dU9P0wLnMjmz0NDtHnck21ALY8qRU+/c3Mgh0s+oBbCX52ogH2IKAMMeAGLY7jhdqZDG4t6eitts4uJcX9l3pgs+IGZO1EgoRwqpg0u+GShTsM9rOqnO+dIOXWeAUgGANiGJJLEtRaxzDUcUJ8AzZOJo8ktwqiSQQwMcVk1EFQg1zNbOCwhkpedhBP9fJZZgTI8S0cx/94omIDKUk0eOdcJWmUlGuoZbpdOfORDPA3bllQbauXUKBTs35bz/zU0SZ7nUStRwAVYzcEs5Lfzk7CbcTIdHkE3AYhDyDSQ8E/kULOFw+tsvOi+wW8oANvAHUxI9VMt+0hUESxfbLsYImZggQDmiprp1L6xy/fo2jhkqhc5sQt4se1lPlPieAB/QmPBqsWTSD2F5CHONf3G0R0OyUgN02IojOThJTTxKhN/NUhOsvLh+sx115+I4qwbsYmvigQzS8HEY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
