appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: 0DlX2w+dcp3ArI6rFZNlPE7imSMB1mKQHFxeoKPJL/ZDyaegPWwNGf7Fi/LEl3pYband3yrpJrpjAFAgkLZzQCQZOimnnh11fnHB9GJxeUrjS+J+ZzeMFPTzcwXQ7TqztzkWC6Xr02Ry+5gX4Uup5Xbahkn4adUe8o5Th6OkuBxqiiC1Gnnh+SjlnmXKRlEyaJ7Xm0bzG7RiqHMztmcNWjR13WpAXR5UPRTTCyfhFpsBiFCyAzbnZ0WDXZsSZlEEPmJk4SW7qGPuQcSQaFD5e/egxmZwFSZJBc1q/agL1FLSjZHCOiPrOIjmtgnFxCYS1lVAMIlp/pfBYxvy4UY1XtRhtaO8aOZQPi5l0qYZSWLzEuT2YdirfFasWVhITWEIMC7HYNAw3I+06Jo4TP1GyZ9m53FSAyXqkmuPnYC13GM7CSfooyrOgfGC3Aggk2w0ISunIzGbf/7xoqQcB8ebT8MpMs6uIop+zSeLRofIpK12RBQhAGpyn7naVqTCswulY8pwdDbzWiMw9bA3pdyJnGXUVyjTnWIydUSwvhdFdDcfabHbTQL7fD9BxvcGJJffkV0RQfu10/4w6fbqsd4KPHr0DTAGbA3EfnBTIUyjUtQ41my7G50hVFa8ZLpm1rFAoGnAzn2TKGhjs9KSkrRqgbDxbUmS4lqzLBY/YnBbCT8=}
