travis:
  secure:
    BINSTAR_TOKEN: wU71PoSHb+N32bVWlItaMOzjNypE7kDbqtA0Eu3JrY8HjMl5nqJL/ILyuMLVmk0MgxC0g4fe7G+kYJ1hIfKRFOfJcSqu/3pob12qrPg0JIOnhcnJQasOOTn5GCAymW3dPkYGjeeUNgpNvIKzIuvNMaXlxLAmQQ3eLr+66POokanE86BRu7TShysup0zBuuZmoqrR+kys7jC4xu3hHerh29lvwwI4b9iWMYH8lTPDzLovyptA5w41+VByPIT/9E6nmkW/EoN8SZb4OyreVMYYvovbP8Ht4cVZo1lOjeAqgJOo0A1c4Lg492mXqiOKLOfO2cwed65//6kdihkIN9wRWYPS3+Klu5lqoD3a7fNS5VsDdOaf8qIUBDUUfXF1NKot0P5tniFu+F8eOgBhWZvZpZV9dVIClpY4xT5f98IKK2FeY9O42FAEDuq3aXxt1kwx9Uw0xhpSfm8qqu/BcT1yk/H6TJ0FzOjpYlIuCnXDimgVCBPPB3atHHYDWfZY/FW+zS8S3W1GapTmAdpkZXLopTOJaQn7TbOcTKK15pAG5PDqZ92CF0n1iXegPUFEmUzbaXDud5bO27r97bS3q+5zI6t8zanj/+z40u8SMmQZ7yoK4FDhmfhNhMwhbvFWDj3XfASBlVO2T9E1+ovXoz5JorRoh5RkZyz2GVM7x/JV/a4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
