travis:
  secure:
    BINSTAR_TOKEN: zM8RZ7SrFaObQrudBbYpjLwnK10Tf2A7bCgj6Iu9ysvMboZI/6TBDDZZG0t51ZQ/LsbW2j9dHh+OsZ3aHw0ARA9sA4agl2TaxBNaXOWigR/pU7VUKdca4DXIt1BzvDcM1ogtkZ01iy26I2qP17I1WxgHj4uqVAeS9fzvdN8HiVbhfT754TatQk61JX2XaF5j9rwjAR3gppWh+odtHeYcZW6niB9vjx3uh5iD7EzBURXpr0/PeTQP31P+dIa5zW7pvBXS7DRVF0Py/qt9JAed67a1/uCjpinWvbmRU6Wjlu9AEKIZR1iT7IwpBq1si2bY3NZMr1Q02w9K7CJ8FHXIh67Bf5D4VRFw2BF/H3O4NjVWJ3uCrssDopUC96Tzx8yeLUgd1sw4DzaSbtb4B49asGV5wrvblIG6igIwtvaQYn8Dh++ollSjad3z0SgageIeFP7gYEgMDi5QDanaC1YjhBXJjcOatMld5yYbjXTaKCCp7sGJZFTS+GqDy5H9yndsyeY9DzBK5Mk//M9LdfefKCVU21GRpQkQki9lTW97KyLZAMV4rjYo9pz/y1lJVFgZ7tJAdXp7kcPrIiykfx6h3711S4Ot6oWQN8vsvmFPq93HnpAMI+AWfmcCmPYBmz0h0KYJZ+1fbqlGv2diQnlXV8Ovb7T4i+oiOQVAI60Zb0k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
